package models

import (
	"github.com/google/uuid"

	"github.com/obluumuu/xor/gen/sqlc"
)

type Tag struct {
	Id    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color *string   `json:"color"`
}

// [Id] is generated by uuid.New()
func NewTagsFromNamesList(names []string) []Tag {
	tags := make([]Tag, 0, len(names))
	for _, name := range names {
		tags = append(tags, Tag{Id: uuid.New(), Name: name})
	}
	return tags
}

func NewFromSqlcTag(tag sqlc.Tag) Tag {
	return Tag{
		Id:    tag.Id,
		Name:  tag.Name,
		Color: tag.Color.Ptr(),
	}
}
